package:
    name:           yii2-asset-hipanel
    namespace:      hiqdev\assets\hipanel
    title:          Yii2 asset for HiPanel logo and so on
    type:           yii2-extension
    keywords:       hipanel, asset, extension, yii2
    year:           2015

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
