package:
    type:           yii2-extension
    name:           yii2-asset-hipanel
    title:          HiPanel assets for Yii2
    headline:       HiPanel Asset
    keywords:       hipanel, asset, extension, yii2
    namespace:      hiqdev\assets\hipanel
    description:    Yii2 asset bundle with HiPanel logo and more

